
# This is a debconf-compatible script
. /usr/share/debconf/confmodule

# TODO: would be nice if I had a custom menu so you could select a machine by name OR roles (maybe list roles as all states...)
machines="$(grep "^[^# ]\+:" /cdrom/data/config-private/salt/etc/machines.yaml)"

# TODO: multiple choice:
# TODO: one of $machines (with colon removed...)
# TODO: or 
# TODO: Custom

# TODO: if previous is Custom
# TODO: text:
# TODO: space separated list of roles
# TODO: else if not Custom
# TODO: set machine to the selected item and move on

# Create the template file
# TODO: maybe this should be generated by generate.sh...
cat > /tmp/config-machine.template <<EOF
Template: installer-ubuntu-config-machine/ask
Type: select
Choices: First, Second, Third
Description: Configuration
 Which machine configuration to install.

Template: installer-ubuntu-config-machine/title
Type: text
Description: Machine
EOF

# Load your template
# TODO: should I be using `db_x_loadtemplatefile /tmp/config-machine.template` instead?
debconf-loadtemplate installer-ubuntu-config-machine /tmp/config-machine.template

# Set title for your custom dialog box
db_settitle installer-ubuntu-config-machine/title

# Ask it!
db_input critical installer-ubuntu-config-machine/ask
db_go

# Get the answer
db_get installer-ubuntu-config-machine/ask

# Save it to a file
machine="$RET"

# TODO: remove
echo "machine: $machine"

if [[ "$machine" == "Custom" ]]; then
	# TODO: prompt for roles
fi

# TODO: set variables
primaryUser="`debconf-get passwd/username`"
machine="laptop-william"
