#!/usr/bin/env sh

# TODO: look at moving this to early_command and saving the variables to a file

# This is a debconf-compatible script
. /usr/share/debconf/confmodule

# Get the list of machine names
machines="$(grep "^[^# ]\+:" /cdrom/data/config-private/salt/etc/machines.yaml)"

# Generate the machine choices list
machine_choices=""
for machine in $machines; do
	machine_choices="${machine_choices}${machine%:}, "
done
machine_choices="${machine_choices}Custom"


# TODO: maybe this should be generated by generate.sh...
# Create the machine choice template
cat > /tmp/config-machine.template <<EOF
Template: installer-ubuntu-config-machine/ask
Type: select
Choices: $machine_choices
Description: Configuration
 Which machine configuration to install.

Template: installer-ubuntu-config-machine/title
Type: text
Description: Machine
EOF

# Load your template
# TODO: should I be using `db_x_loadtemplatefile /tmp/config-machine.template` instead?
debconf-loadtemplate installer-ubuntu-config-machine /tmp/config-machine.template

# Set title for your custom dialog box
db_settitle installer-ubuntu-config-machine/title

# Ask it!
db_input critical installer-ubuntu-config-machine/ask
db_go

# Get the answer
db_get installer-ubuntu-config-machine/ask

# Save it to a file
machine="$RET"


if [ "$machine" = "Custom" ];
then
	# Reset Machine
	machine=""

	# TODO: maybe this should be generated by generate.sh...
	# Create the roles choice template
	cat > /tmp/config-roles.template <<EOF
Template: installer-ubuntu-config-roles/ask
Type: string
Description: Roles
 Which roles to install.

Template: installer-ubuntu-config-roles/title
Type: text
Description: Custom
EOF

	# Load your template
	# TODO: should I be using `db_x_loadtemplatefile /tmp/config-roles.template` instead?
	debconf-loadtemplate installer-ubuntu-config-roles /tmp/config-roles.template

	# Set title for your custom dialog box
	db_settitle installer-ubuntu-config-roles/title

	# Ask it!
	db_input critical installer-ubuntu-config-roles/ask
	db_go

	# Get the answer
	db_get installer-ubuntu-config-roles/ask

	# Save it to a file
	roles="$RET"
fi

# set remaining variables
primaryUser="`debconf-get passwd/username`"
